<a href="https://colab.research.google.com/github/Prathibha-bm/take_it_smart/blob/main/class11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
nums=np.array([2,14,35,23,12,6,7,90])
print(nums)
for i in nums:
  if i%2 ==0 or i>10:
    print(i)

output=nums[(nums%2==0)|(nums>10)]
print(output)

[ 2 14 35 23 12  6  7 90]
2
14
35
23
12
6
90
[ 2 14 35 23 12  6 90]


Indexing and slicing


In [ ]:
nums=np.array([2,14,35,23,12,6,7,90])
print(nums[0])
print(nums[1:4])
#2 array
nums=np.array([[1,2,3],[4,5,6]])
print([1,2])

age=np.array([56,78,89,90,56,45,67]).reshape(7,1)
a=np.arange(1,10)
print(nums)

2
[14 35 23]
[1, 2]
[[1 2 3]
 [4 5 6]]


#Task3.1
1.Create an array and find sum and avg of all the elements in an array


In [ ]:
import numpy as np
nums=np.array([1,3,6,3,7,5,8,4,97,4346,567,36,5644])
total=0
count=0
for i in nums:
    total=total + i
    count=count + 1
avg=total/count
print(nums)
print("Total sum :", total)
print("average of all elements :", avg)


[   1    3    6    3    7    5    8    4   97 4346  567   36 5644]
Total sum : 10727
average of all elements : 825.1538461538462
