<a href="https://colab.research.google.com/github/Prathibha-bm/take_it_smart/blob/main/class13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Functions in numpy

In [ ]:
import numpy as np
nums=np.array([2,3,4,5,6])
copied =nums.copy()
print(nums,copied)
nums[0]=34
print(nums,copied)

#view
viewnum=nums.view()
nums[0]=45
print(viewnum,nums)

arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)
print(arr.reshape(2,2,-1))

for i in arr:
  for j in i:
    print(j)



[2 3 4 5 6] [2 3 4 5 6]
[34  3  4  5  6] [2 3 4 5 6]
[45  3  4  5  6] [45  3  4  5  6]
(2, 4)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
1
2
3
4
5
6
7
8



#nditer function


In [ ]:
arr=np.array([[[1,2,3,4],[5,6,7,8]]])
for i in np.nditer(arr):
  print(i)

1
2
3
4
5
6
7
8


#join


In [ ]:
n1=np.array([[2,3,4],[5,6,7,]])
n2=np.array([[2,3,4],[5,6,8]])
x=np.concatenate((n1,n2), axis=1)
print(x)

'''
axis=0 row wise addition
axis=1 column wise addition'''


[[2 3 4 2 3 4]
 [5 6 7 5 6 8]]


#split


In [ ]:
#split
n1=np.array([2,3,4,5,6,7])
x=np.array_split(n1,4)
print(x)

[array([2, 3]), array([4, 5]), array([6]), array([7])]


#search


In [ ]:
#search
n1=np.array([2,3,4,5,6,7])
x=np.where(n1==4)
print(x)

(array([2]),)


In [ ]:
n1=np.array([2,3,4,5,6,7])
x=np.where(n1%2==0)
print(x)

(array([0, 2, 4]),)


#searchsort

In [ ]:
#searchsort: it does't search the elements instead it sorts the array and gives the sorted index of the element
n1=np.array([2,3,4,5,6,7])
x=np.searchsorted(n1,8)
print(x)

6


#sort function


In [ ]:
#sort function
n2=np.array([[223,30,45],[5,6,8]])
x=np.sort(n2)
print(x)

[[2 3 4]
 [5 6 8]]


In [ ]:
n2=np.array([True,False,True])
x=np.sort(n2)
print(x)

[False  True  True]


#filtering

In [ ]:
#filtering: getting some elements out of an existingn array and creating a new array out of them is called filterinh
#a boolean index list is a list of boolean corresponding to indexs in array
n2=np.array([223,30,45,6])
filtered =[True,False,True,False]
new=n2[filtered]
print(new)

[223  45]


In [ ]:
f_arr=[]
for i in n2:
  if i <222:
    f_arr.append(True)
  else:
      f_arr.append(False)
new=n2[f_arr]
print(new,f_arr)

[30 45  6] [False, True, True, True]


#Task 3.3

1.Get NumPy Version & Build Info

write a numpy program to get the numpy version and show the numpy build configuration.

In [7]:
import numpy as np
print(f"NumPy Version: {np.__version__}")

print("NumPy Build Configuration:")
np.show_config()

NumPy Version: 2.0.2
NumPy Build Configuration:
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
  

2.Help for numPy Add Function

write a numpy program to get help with the add function.Programming

In [6]:
import numpy as np
print("NumPy Info for 'add'")
help(np.add)

NumPy Info for 'add'
Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` arr

3.Test none are Zero

write a Numpy program to test whether none of the elements of a given array are zero.

In [24]:
import numpy as np
nums=np.array([10, 20, 30, 40])

if none_are_zero:
    print("Result: Success! None of the elements are zero.")
else:
    print("Result: Found it! At least one element is zero.")

Result: Success! None of the elements are zero.
